[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@pancakeswap/=lib/pancake-smart-contracts/",
    "@uniswap/universal-router/=lib/universal-router/",
    "@uniswap/permit2/=lib/permit2/",
    "v4-core/=lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
]

# Enable IR-based code generation for handling deep stacks
via_ir = true

# Enable optimization
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
